import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { Geist, Geist_Mono } from 'next/font/google';

import WalletConnectionGuard from '@/components/auth/WalletConnectionGuard';
import { Toaster } from '@/components/ui/sonner';

import { GlobalProvider } from '@/providers/globalProvider';

import '@rainbow-me/rainbowkit/styles.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await headers()).get('cookie');

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GlobalProvider cookie={cookie}>
          <WalletConnectionGuard>{children} </WalletConnectionGuard>
        </GlobalProvider>

        <Toaster />
      </body>
    </html>
  );
}
